//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grade_Monitoring.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class grade_monitoringEntities : DbContext
    {
        public grade_monitoringEntities()
            : base("name=grade_monitoringEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<course_info> course_info { get; set; }
        public virtual DbSet<faculty_subject> faculty_subject { get; set; }
        public virtual DbSet<faculty_table> faculty_table { get; set; }
        public virtual DbSet<student_block> student_block { get; set; }
        public virtual DbSet<student_info> student_info { get; set; }
        public virtual DbSet<student_subject> student_subject { get; set; }
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
        public virtual DbSet<tbl_student_subject> tbl_student_subject { get; set; }
        public virtual DbSet<tbl_student_grade> tbl_student_grade { get; set; }
    }
}
