//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grade_Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student_info()
        {
            this.tbl_student_subject = new HashSet<tbl_student_subject>();
            this.tbl_student_grade = new HashSet<tbl_student_grade>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string location { get; set; }
        public string email_address { get; set; }
        public string phone_number { get; set; }
        public string student_block { get; set; }
        public string stud_username { get; set; }
        public string stud_password { get; set; }
        public string year_lvl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_subject> tbl_student_subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_grade> tbl_student_grade { get; set; }
    }
}
