//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grade_Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student_subject()
        {
            this.faculty_subject = new HashSet<faculty_subject>();
            this.tbl_student_subject = new HashSet<tbl_student_subject>();
            this.tbl_student_grade = new HashSet<tbl_student_grade>();
        }
    
        public int id { get; set; }
        public string subject_code { get; set; }
        public string subject_name { get; set; }
        public string year_level { get; set; }
        public int subject_unit { get; set; }
        public string per_sem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<faculty_subject> faculty_subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_subject> tbl_student_subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_grade> tbl_student_grade { get; set; }
    }
}
