//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grade_Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_grade
    {
        public int id { get; set; }
        public int student_id { get; set; }
        public int subject_id { get; set; }
        public decimal? first_sem { get; set; }
        public decimal? second_sem { get; set; }
        public decimal? final_result { get; set; }
    
        public virtual student_info student_info { get; set; }
        public virtual student_subject student_subject { get; set; }
    }
}
